import type { AHLTeamTypeReal } from "~/data/NHL/NHLdata";
import type { StyleBookType } from "~/types/StyleBook";

export const AHLstyleData: { [Key in AHLTeamTypeReal] : StyleBookType} = {
  ABB:{
    primary: "#047835",
    secondary: "#0E1C2C",
    primaryBackground: "bg-[#047835]",
    primaryBackgroundHover: "hover:bg-[#047835]",
    secondaryBorder: "border-[#0E1C2C]",
    secondaryBorderHover: "hover:border-[#0E1C2C]",
    secondaryText: "text-[#0E1C2C]",
    secondaryTextHover: "hover:text-[#0E1C2C]",
    simpleText: "text-[#FFFFFF]",
    simpleTextHover: "hover:text-[#FFFFFF]",
  },
  BAK:{
    primary: "#152342",
    secondary: "#DF4E10",
    primaryBackground: "bg-[#152342]",
    primaryBackgroundHover: "hover:bg-[#152342]",
    secondaryBorder: "border-[#DF4E10]",
    secondaryBorderHover: "hover:border-[#DF4E10]",
    secondaryText: "text-[#DF4E10]",
    secondaryTextHover: "hover:text-[#DF4E10]",
    simpleText: "text-[#FFFFFF]",
    simpleTextHover: "hover:text-[#FFFFFF]",
  },
  BEL:{
    primary: "#E3173E",
    secondary: "#000000",
    primaryBackground: "bg-[#E3173E]",
    primaryBackgroundHover: "hover:bg-[#E3173E]",
    secondaryBorder: "border-[#000000]",
    secondaryBorderHover: "hover:border-[#000000]",
    secondaryText: "text-[#000000]",
    secondaryTextHover: "hover:text-[#000000]",
    simpleText: "text-[#FFFFFF]",
    simpleTextHover: "hover:text-[#FFFFFF]",
  },
  CGY:{
    primary: "#C2273D",
    secondary: "#F3BD48",
    primaryBackground: "bg-[#C2273D]",
    primaryBackgroundHover: "hover:bg-[#C2273D]",
    secondaryBorder: "border-[#F3BD48]",
    secondaryBorderHover: "hover:border-[#F3BD48]",
    secondaryText: "text-[#F3BD48]",
    secondaryTextHover: "hover:text-[#F3BD48]",
    simpleText: "text-[#FFFFFF]",
    simpleTextHover: "hover:text-[#FFFFFF]",
  },
  CHI:{
    primary: "#939283",
    secondary: "#000000",
    primaryBackground: "bg-[#939283]",
    primaryBackgroundHover: "hover:bg-[#939283]",
    secondaryBorder: "border-[#000000]",
    secondaryBorderHover: "hover:border-[#000000]",
    secondaryText: "text-[#000000]",
    secondaryTextHover: "hover:text-[#000000]",
    simpleText: "text-[#FFFFFF]",
    simpleTextHover: "hover:text-[#FFFFFF]",
  },
  CLE:{
    primary: "#005695",
    secondary: "#000000",
    primaryBackground: "bg-[#005695]",
    primaryBackgroundHover: "hover:bg-[#005695]",
    secondaryBorder: "border-[#000000]",
    secondaryBorderHover: "hover:border-[#000000]",
    secondaryText: "text-[#000000]",
    secondaryTextHover: "hover:text-[#000000]",
    simpleText: "text-[#FFFFFF]",
    simpleTextHover: "hover:text-[#FFFFFF]",
  },
  CLT:{
    primary: "#E51A38",
    secondary: "#000000",
    primaryBackground: "bg-[#E51A38]",
    primaryBackgroundHover: "hover:bg-[#E51A38]",
    secondaryBorder: "border-[#000000]",
    secondaryBorderHover: "hover:border-[#000000]",
    secondaryText: "text-[#000000]",
    secondaryTextHover: "hover:text-[#000000]",
    simpleText: "text-[#FFFFFF]",
    simpleTextHover: "hover:text-[#FFFFFF]",
  },
  COL:{
    primary: "#19398A",
    secondary: "#FFD457",
    primaryBackground: "bg-[#19398A]",
    primaryBackgroundHover: "hover:bg-[#19398A]",
    secondaryBorder: "border-[#FFD457]",
    secondaryBorderHover: "hover:border-[#FFD457]",
    secondaryText: "text-[#FFD457]",
    secondaryTextHover: "hover:text-[#FFD457]",
    simpleText: "text-[#FFFFFF]",
    simpleTextHover: "hover:text-[#FFFFFF]",
  },
  CVF:{
    primary: "#C8102E",
    secondary: "#FF681D",
    primaryBackground: "bg-[#C8102E]",
    primaryBackgroundHover: "hover:bg-[#C8102E]",
    secondaryBorder: "border-[#FF681D]",
    secondaryBorderHover: "hover:border-[#FF681D]",
    secondaryText: "text-[#FF681D]",
    secondaryTextHover: "hover:text-[#FF681D]",
    simpleText: "text-[#FFFFFF]",
    simpleTextHover: "hover:text-[#FFFFFF]",
  },
  GRG:{
    primary: "#866C3F",
    secondary: "#000000",
    primaryBackground: "bg-[#866C3F]",
    primaryBackgroundHover: "hover:bg-[#866C3F]",
    secondaryBorder: "border-[#000000]",
    secondaryBorderHover: "hover:border-[#000000]",
    secondaryText: "text-[#000000]",
    secondaryTextHover: "hover:text-[#000000]",
    simpleText: "text-[#FFFFFF]",
    simpleTextHover: "hover:text-[#FFFFFF]",
  },
  HAM:{
    primary: "#00468B",
    secondary: "#F26924",
    primaryBackground: "bg-[#00468B]",
    primaryBackgroundHover: "hover:bg-[#00468B]",
    secondaryBorder: "border-[#F26924]",
    secondaryBorderHover: "hover:border-[#F26924]",
    secondaryText: "text-[#F26924]",
    secondaryTextHover: "hover:text-[#F26924]",
    simpleText: "text-[#FFFFFF]",
    simpleTextHover: "hover:text-[#FFFFFF]",
  },
  HER:{
    primary: "#7E543A",
    secondary: "#E7D2AD",
    primaryBackground: "bg-[#7E543A]",
    primaryBackgroundHover: "hover:bg-[#7E543A]",
    secondaryBorder: "border-[#E7D2AD]",
    secondaryBorderHover: "hover:border-[#E7D2AD]",
    secondaryText: "text-[#E7D2AD]",
    secondaryTextHover: "hover:text-[#E7D2AD]",
    simpleText: "text-[#FFFFFF]",
    simpleTextHover: "hover:text-[#FFFFFF]",
  },
  HFD:{
    primary: "#00548E",
    secondary: "#EF3E42",
    primaryBackground: "bg-[#00548E]",
    primaryBackgroundHover: "hover:bg-[#00548E]",
    secondaryBorder: "border-[#EF3E42]",
    secondaryBorderHover: "hover:border-[#EF3E42]",
    secondaryText: "text-[#EF3E42]",
    secondaryTextHover: "hover:text-[#EF3E42]",
    simpleText: "text-[#FFFFFF]",
    simpleTextHover: "hover:text-[#FFFFFF]",
  },
  HSK:{
    primary: "#C2C4C6",
    secondary: "#000000",
    primaryBackground: "bg-[#C2C4C6]",
    primaryBackgroundHover: "hover:bg-[#C2C4C6]",
    secondaryBorder: "border-[#000000]",
    secondaryBorderHover: "hover:border-[#000000]",
    secondaryText: "text-[#000000]",
    secondaryTextHover: "hover:text-[#000000]",
    simpleText: "text-[#FFFFFF]",
    simpleTextHover: "hover:text-[#FFFFFF]",
  },
    MBM:{
    primary: "#041E41",
    secondary: "#A4A9AD",
    primaryBackground: "bg-[#041E41]",
    primaryBackgroundHover: "hover:bg-[#041E41]",
    secondaryBorder: "border-[#A4A9AD]",
    secondaryBorderHover: "hover:border-[#A4A9AD]",
    secondaryText: "text-[#A4A9AD]",
    secondaryTextHover: "hover:text-[#A4A9AD]",
    simpleText: "text-[#FFFFFF]",
    simpleTextHover: "hover:text-[#FFFFFF]",
  },
  IOW:{
    primary: "#154734",
    secondary: "#EAAA00",
    primaryBackground: "bg-[#154734]",
    primaryBackgroundHover: "hover:bg-[#154734]",
    secondaryBorder: "border-[#EAAA00]",
    secondaryBorderHover: "hover:border-[#EAAA00]",
    secondaryText: "text-[#EAAA00]",
    secondaryTextHover: "hover:text-[#EAAA00]",
    simpleText: "text-[#FFFFFF]",
    simpleTextHover: "hover:text-[#FFFFFF]",
  },
  LAV:{
    primary: "#001E61",
    secondary: "#FFFFFF",
    primaryBackground: "bg-[#001E61]",
    primaryBackgroundHover: "hover:bg-[#001E61]",
    secondaryBorder: "border-[#FFFFFF]",
    secondaryBorderHover: "hover:border-[#FFFFFF]",
    secondaryText: "text-[#FFFFFF]",
    secondaryTextHover: "hover:text-[#FFFFFF]",
    simpleText: "text-[#FFFFFF]",
    simpleTextHover: "hover:text-[#FFFFFF]",
  },
  LVP:{
    primary: "#F58220",
    secondary: "#000000",
    primaryBackground: "bg-[#F58220]",
    primaryBackgroundHover: "hover:bg-[#F58220]",
    secondaryBorder: "border-[#000000]",
    secondaryBorderHover: "hover:border-[#000000]",
    secondaryText: "text-[#000000]",
    secondaryTextHover: "hover:text-[#000000]",
    simpleText: "text-[#FFFFFF]",
    simpleTextHover: "hover:text-[#FFFFFF]",
  },
  MIL:{
    primary: "#0E2B58",
    secondary: "#83C2EC",
    primaryBackground: "bg-[#0E2B58]",
    primaryBackgroundHover: "hover:bg-[#0E2B58]",
    secondaryBorder: "border-[#83C2EC]",
    secondaryBorderHover: "hover:border-[#83C2EC]",
    secondaryText: "text-[#83C2EC]",
    secondaryTextHover: "hover:text-[#83C2EC]",
    simpleText: "text-[#FFFFFF]",
    simpleTextHover: "hover:text-[#FFFFFF]",
  },
  ONT:{
    primary: "#000000",
    secondary: "#A4A9AD",
    primaryBackground: "bg-[#000000]",
    primaryBackgroundHover: "hover:bg-[#000000]",
    secondaryBorder: "border-[#A4A9AD]",
    secondaryBorderHover: "hover:border-[#A4A9AD]",
    secondaryText: "text-[#A4A9AD]",
    secondaryTextHover: "hover:text-[#A4A9AD]",
    simpleText: "text-[#FFFFFF]",
    simpleTextHover: "hover:text-[#FFFFFF]",
  },
  PRO:{
    primary: "#FBB337",
    secondary: "#000000",
    primaryBackground: "bg-[#FBB337]",
    primaryBackgroundHover: "hover:bg-[#FBB337]",
    secondaryBorder: "border-[#000000]",
    secondaryBorderHover: "hover:border-[#000000]",
    secondaryText: "text-[#000000]",
    secondaryTextHover: "hover:text-[#000000]",
    simpleText: "text-[#FFFFFF]",
    simpleTextHover: "hover:text-[#FFFFFF]",
  },
  RFD:{
    primary: "#DB1931",
    secondary: "#000000",
    primaryBackground: "bg-[#DB1931]",
    primaryBackgroundHover: "hover:bg-[#DB1931]",
    secondaryBorder: "border-[#000000]",
    secondaryBorderHover: "hover:border-[#000000]",
    secondaryText: "text-[#000000]",
    secondaryTextHover: "hover:text-[#000000]",
    simpleText: "text-[#FFFFFF]",
    simpleTextHover: "hover:text-[#FFFFFF]",
  },
  ROC:{
    primary: "#393A87",
    secondary: "#DE2944",
    primaryBackground: "bg-[#393A87]",
    primaryBackgroundHover: "hover:bg-[#393A87]",
    secondaryBorder: "border-[#DE2944]",
    secondaryBorderHover: "hover:border-[#DE2944]",
    secondaryText: "text-[#DE2944]",
    secondaryTextHover: "hover:text-[#DE2944]",
    simpleText: "text-[#FFFFFF]",
    simpleTextHover: "hover:text-[#FFFFFF]",
  },
  SDG:{
    primary: "#FF4C00",
    secondary: "#000000",
    primaryBackground: "bg-[#FF4C00]",
    primaryBackgroundHover: "hover:bg-[#FF4C00]",
    secondaryBorder: "border-[#000000]",
    secondaryBorderHover: "hover:border-[#000000]",
    secondaryText: "text-[#000000]",
    secondaryTextHover: "hover:text-[#000000]",
    simpleText: "text-[#FFFFFF]",
    simpleTextHover: "hover:text-[#FFFFFF]",
  },
  SJB:{
    primary: "#266B73",
    secondary: "#000000",
    primaryBackground: "bg-[#266B73]",
    primaryBackgroundHover: "hover:bg-[#266B73]",
    secondaryBorder: "border-[#000000]",
    secondaryBorderHover: "hover:border-[#000000]",
    secondaryText: "text-[#000000]",
    secondaryTextHover: "hover:text-[#000000]",
    simpleText: "text-[#FFFFFF]",
    simpleTextHover: "hover:text-[#FFFFFF]",
  },
  SPR:{
    primary: "#005CB9",
    secondary: "#FFC425",
    primaryBackground: "bg-[#005CB9]",
    primaryBackgroundHover: "hover:bg-[#005CB9]",
    secondaryBorder: "border-[#FFC425]",
    secondaryBorderHover: "hover:border-[#FFC425]",
    secondaryText: "text-[#FFC425]",
    secondaryTextHover: "hover:text-[#FFC425]",
    simpleText: "text-[#FFFFFF]",
    simpleTextHover: "hover:text-[#FFFFFF]",
  },
  SYR:{
    primary: "#1D427C",
    secondary: "#AAA9AC",
    primaryBackground: "bg-[#1D427C]",
    primaryBackgroundHover: "hover:bg-[#1D427C]",
    secondaryBorder: "border-[#AAA9AC]",
    secondaryBorderHover: "hover:border-[#AAA9AC]",
    secondaryText: "text-[#AAA9AC]",
    secondaryTextHover: "hover:text-[#AAA9AC]",
    simpleText: "text-[#FFFFFF]",
    simpleTextHover: "hover:text-[#FFFFFF]",
  },
  TEX:{
    primary: "#1B6031",
    secondary: "#A5A6A8",
    primaryBackground: "bg-[#1B6031]",
    primaryBackgroundHover: "hover:bg-[#1B6031]",
    secondaryBorder: "border-[#A5A6A8]",
    secondaryBorderHover: "hover:border-[#A5A6A8]",
    secondaryText: "text-[#A5A6A8]",
    secondaryTextHover: "hover:text-[#A5A6A8]",
    simpleText: "text-[#FFFFFF]",
    simpleTextHover: "hover:text-[#FFFFFF]",
  },
  TOR:{
    primary: "#003E7E",
    secondary: "#FFC425",
    primaryBackground: "bg-[#003E7E]",
    primaryBackgroundHover: "hover:bg-[#003E7E]",
    secondaryBorder: "border-[#FFC425]",
    secondaryBorderHover: "hover:border-[#FFC425]",
    secondaryText: "text-[#FFC425]",
    secondaryTextHover: "hover:text-[#FFC425]",
    simpleText: "text-[#FFFFFF]",
    simpleTextHover: "hover:text-[#FFFFFF]",
  },
  TUC:{
    primary: "#8E0A26",
    secondary: "#AB724B",
    primaryBackground: "bg-[#8E0A26]",
    primaryBackgroundHover: "hover:bg-[#8E0A26]",
    secondaryBorder: "border-[#AB724B]",
    secondaryBorderHover: "hover:border-[#AB724B]",
    secondaryText: "text-[#AB724B]",
    secondaryTextHover: "hover:text-[#AB724B]",
    simpleText: "text-[#FFFFFF]",
    simpleTextHover: "hover:text-[#FFFFFF]",
  },
  UTI:{
    primary: "#CF2031",
    secondary: "#000000",
    primaryBackground: "bg-[#CF2031]",
    primaryBackgroundHover: "hover:bg-[#CF2031]",
    secondaryBorder: "border-[#000000]",
    secondaryBorderHover: "hover:border-[#000000]",
    secondaryText: "text-[#000000]",
    secondaryTextHover: "hover:text-[#000000]",
    simpleText: "text-[#FFFFFF]",
    simpleTextHover: "hover:text-[#FFFFFF]",
  },
  WBS:{
    primary: "#FEC23D",
    secondary: "#000000",
    primaryBackground: "bg-[#FEC23D]",
    primaryBackgroundHover: "hover:bg-[#FEC23D]",
    secondaryBorder: "border-[#000000]",
    secondaryBorderHover: "hover:border-[#000000]",
    secondaryText: "text-[#000000]",
    secondaryTextHover: "hover:text-[#000000]",
    simpleText: "text-[#FFFFFF]",
    simpleTextHover: "hover:text-[#FFFFFF]",
  },
}