import type { AHLTeamTypeReal } from "~/data/NHL/NHLdata";
import type { StyleBookType } from "~/types/StyleBook";

export const AHLstyleData: { [Key in AHLTeamTypeReal] : StyleBookType} = {
  ABB:{
    primary: "#047835",
    secondary: "#0E1C2C",
    primaryBackground: "bg-[#047835]",
    secondaryBorder: "border-[#0E1C2C]",
    secondaryText: "text-[#0E1C2C]",
    simpleText: "text-[#FFFFFF]",
  },
  BAK:{
    primary: "#041E42",
    secondary: "#FF4C00",
    primaryBackground: "bg-[#041E42]",
    secondaryBorder: "border-[#FF4C00]",
    secondaryText: "text-[#FF4C00]",
    simpleText: "text-[#FFFFFF]",
  },
  BEL:{
    primary: "#000000",
    secondary: "#DA1A32",
    primaryBackground: "bg-[#000000]",
    secondaryBorder: "border-[#DA1A32]",
    secondaryText: "text-[#DA1A32]",
    simpleText: "text-[#FFFFFF]",
  },
  CGY:{
    primary: "#D2001C",
    secondary: "#FAAF19",
    primaryBackground: "bg-[#D2001C]",
    secondaryBorder: "border-[#FAAF19]",
    secondaryText: "text-[#FAAF19]",
    simpleText: "text-[#FFFFFF]",
  },
  CHI:{
    primary: "#939283",
    secondary: "#000000",
    primaryBackground: "bg-[#939283]",
    secondaryBorder: "border-[#000000]",
    secondaryText: "text-[#000000]",
    simpleText: "text-[#FFFFFF]",
  },
  CLE:{
    primary: "#005695",
    secondary: "#000000",
    primaryBackground: "bg-[#005695]",
    secondaryBorder: "border-[#000000]",
    secondaryText: "text-[#000000]",
    simpleText: "text-[#FFFFFF]",
  },
  CLT:{
    primary: "#E51A38",
    secondary: "#000000",
    primaryBackground: "bg-[#E51A38]",
    secondaryBorder: "border-[#000000]",
    secondaryText: "text-[#000000]",
    simpleText: "text-[#FFFFFF]",
  },
  COL:{
    primary: "#19398A",
    secondary: "#FFD457",
    primaryBackground: "bg-[#19398A]",
    secondaryBorder: "border-[#FFD457]",
    secondaryText: "text-[#FFD457]",
    simpleText: "text-[#FFFFFF]",
  },
  CVF:{
    primary: "#C8102E",
    secondary: "#FF681D",
    primaryBackground: "bg-[#C8102E]",
    secondaryBorder: "border-[#FF681D]",
    secondaryText: "text-[#FF681D]",
    simpleText: "text-[#FFFFFF]",
  },
  GRG:{
    primary: "#866C3F",
    secondary: "#000000",
    primaryBackground: "bg-[#866C3F]",
    secondaryBorder: "border-[#000000]",
    secondaryText: "text-[#000000]",
    simpleText: "text-[#FFFFFF]",
  },
  HAM:{
    primary: "#00539B",
    secondary: "#F47D30",
    primaryBackground: "bg-[#00539B]",
    secondaryBorder: "border-[#F47D30]",
    secondaryText: "text-[#F47D30]",
    simpleText: "text-[#FFFFFF]",
  },
  HER:{
    primary: "#7E543A",
    secondary: "#E7D2AD",
    primaryBackground: "bg-[#7E543A]",
    secondaryBorder: "border-[#E7D2AD]",
    secondaryText: "text-[#E7D2AD]",
    simpleText: "text-[#FFFFFF]",
  },
  HFD:{
    primary: "#0038A8",
    secondary: "#CE1126",
    primaryBackground: "bg-[#0038A8]",
    secondaryBorder: "border-[#CE1126]",
    secondaryText: "text-[#CE1126]",
    simpleText: "text-[#FFFFFF]",
  },
  HSK:{
    primary: "#C2C4C6",
    secondary: "#000000",
    primaryBackground: "bg-[#C2C4C6]",
    secondaryBorder: "border-[#000000]",
    secondaryText: "text-[#000000]",
    simpleText: "text-[#000000]",
  },
  IOW:{
    primary: "#154734",
    secondary: "#A6192E",
    primaryBackground: "bg-[#154734]",
    secondaryBorder: "border-[#A6192E]",
    secondaryText: "text-[#A6192E]",
    simpleText: "text-[#FFFFFF]",
  },
  LAV:{
    primary: "#001E61",
    secondary: "#FFFFFF",
    primaryBackground: "bg-[#001E61]",
    secondaryBorder: "border-[#FFFFFF]",
    secondaryText: "text-[#FFFFFF]",
    simpleText: "text-[#FFFFFF]",
  },
  LVP:{
    primary: "#F74902",
    secondary: "#000000",
    primaryBackground: "bg-[#F74902]",
    secondaryBorder: "border-[#000000]",
    secondaryText: "text-[#000000]",
    simpleText: "text-[#000000]",
  },
  MBM:{
    primary: "#041E42",
    secondary: "#8E9090",
    primaryBackground: "bg-[#041E42]",
    secondaryBorder: "border-[#8E9090]",
    secondaryText: "text-[#8E9090]",
    simpleText: "text-[#FFFFFF]",
  },
  MIL:{
    primary: "#0E2B58",
    secondary: "#83C2EC",
    primaryBackground: "bg-[#0E2B58]",
    secondaryBorder: "border-[#83C2EC]",
    secondaryText: "text-[#83C2EC]",
    simpleText: "text-[#FFFFFF]",
  },
  ONT:{
    primary: "#111111",
    secondary: "#A2AAAD",
    primaryBackground: "bg-[#111111]",
    secondaryBorder: "border-[#A2AAAD]",
    secondaryText: "text-[#A2AAAD]",
    simpleText: "text-[#FFFFFF]",
  },
  PRO:{
    primary: "#FFB81C",
    secondary: "#000000",
    primaryBackground: "bg-[#FFB81C]",
    secondaryBorder: "border-[#000000]",
    secondaryText: "text-[#000000]",
    simpleText: "text-[#000000]",
  },
  RFD:{
    primary: "#DB1931",
    secondary: "#000000",
    primaryBackground: "bg-[#DB1931]",
    secondaryBorder: "border-[#000000]",
    secondaryText: "text-[#000000]",
    simpleText: "text-[#FFFFFF]",
  },
  ROC:{
    primary: "#393A87",
    secondary: "#DE2944",
    primaryBackground: "bg-[#393A87]",
    secondaryBorder: "border-[#DE2944]",
    secondaryText: "text-[#DE2944]",
    simpleText: "text-[#FFFFFF]",
  },
  SDG:{
    primary: "#FF4C00",
    secondary: "#000000",
    primaryBackground: "bg-[#FF4C00]",
    secondaryBorder: "border-[#000000]",
    secondaryText: "text-[#000000]",
    simpleText: "text-[#FFFFFF]",
  },
  SJB:{
    primary: "#006D75",
    secondary: "#EA7200",
    primaryBackground: "bg-[#006D75]",
    secondaryBorder: "border-[#EA7200]",
    secondaryText: "text-[#EA7200]",
    simpleText: "text-[#FFFFFF]",
  },
  SPR:{
    primary: "#005CB9",
    secondary: "#FFC425",
    primaryBackground: "bg-[#005CB9]",
    secondaryBorder: "border-[#FFC425]",
    secondaryText: "text-[#FFC425]",
    simpleText: "text-[#FFFFFF]",
  },
  SYR:{
    primary: "#002868",
    secondary: "#AAA9AC",
    primaryBackground: "bg-[#002868]",
    secondaryBorder: "border-[#AAA9AC]",
    secondaryText: "text-[#AAA9AC]",
    simpleText: "text-[#FFFFFF]",
  },
  TEX:{
    primary: "#006847",
    secondary: "#8F8F8C",
    primaryBackground: "bg-[#006847]",
    secondaryBorder: "border-[#8F8F8C]",
    secondaryText: "text-[#8F8F8C]",
    simpleText: "text-[#FFFFFF]",
  },
  TOR:{
    primary: "#003E7E",
    secondary: "#FFC425",
    primaryBackground: "bg-[#003E7E]",
    secondaryBorder: "border-[#FFC425]",
    secondaryText: "text-[#FFC425]",
    simpleText: "text-[#FFFFFF]",
  },
  TUC:{
    primary: "#8E0A26",
    secondary: "#AB724B",
    primaryBackground: "bg-[#8E0A26]",
    secondaryBorder: "border-[#AB724B]",
    secondaryText: "text-[#AB724B]",
    simpleText: "text-[#FFFFFF]",
  },
  UTI:{
    primary: "#CE1126",
    secondary: "#000000",
    primaryBackground: "bg-[#CE1126]",
    secondaryBorder: "border-[#000000]",
    secondaryText: "text-[#000000]",
    simpleText: "text-[#FFFFFF]",
  },
  WBS:{
    primary: "#000000",
    secondary: "#CFC493",
    primaryBackground: "bg-[#000000]",
    secondaryBorder: "border-[#CFC493]",
    secondaryText: "text-[#CFC493]",
    simpleText: "text-[#FFFFFF]",
  },
}