import type { AllCFLTeamType } from "~/data/CFL/CFLdata";
import { type StyleBookType } from "~/types/StyleBook";

export const CFLstyleData: { [Key in AllCFLTeamType] : StyleBookType} = {
  BAL:{
    primary: "#002D72",
    secondary: "#95908D",
    primaryBackground: "bg-[#002D72]",
    secondaryBorder: "border-[#95908D]",
    secondaryText: "text-[#95908D]",
    simpleText: "text-[#FFFFFF]",
  },
  BCL:{
    primary: "#FC4C02",
    secondary: "#000000",
    primaryBackground: "bg-[#FC4C02]",
    secondaryBorder: "border-[#000000]",
    secondaryText: "text-[#000000]",
    simpleText: "text-[#FFFFFF]",
  },
  CGY:{
    primary: "#C8102E",
    secondary: "#FFFFFF",
    primaryBackground: "bg-[#C8102E]",
    secondaryBorder: "border-[#FFFFFF]",
    secondaryText: "text-[#FFFFFF]",
    simpleText: "text-[#FFFFFF]",
  },
  EDM:{
    primary: "#2C5234",
    secondary: "#FFB81C",
    primaryBackground: "bg-[#2C5234]",
    secondaryBorder: "border-[#FFB81C]",
    secondaryText: "text-[#FFB81C]",
    simpleText: "text-[#FFFFFF]",
  },
  ESK:{
    primary: "#2C5234",
    secondary: "#FFB81C",
    primaryBackground: "bg-[#2C5234]",
    secondaryBorder: "border-[#FFB81C]",
    secondaryText: "text-[#FFB81C]",
    simpleText: "text-[#FFFFFF]",
  },
  HAM:{
    primary: "#FFB81C",
    secondary: "#000000",
    primaryBackground: "bg-[#FFB81C]",
    secondaryBorder: "border-[#000000]",
    secondaryText: "text-[#000000]",
    simpleText: "text-[#000000]",
  },
  MTL:{
    primary: "#071D49",
    secondary: "#C8102E",
    primaryBackground: "bg-[#071D49]",
    secondaryBorder: "border-[#C8102E]",
    secondaryText: "text-[#C8102E]",
    simpleText: "text-[#FFFFFF]",
  },
  ORR:{
    primary: "#000000",
    secondary: "#C8102E",
    primaryBackground: "bg-[#000000]",
    secondaryBorder: "border-[#C8102E]",
    secondaryText: "text-[#C8102E]",
    simpleText: "text-[#FFFFFF]",
  },
  OTT:{
    primary: "#A6192E",
    secondary: "#000000",
    primaryBackground: "bg-[#A6192E]",
    secondaryBorder: "border-[#000000]",
    secondaryText: "text-[#000000]",
    simpleText: "text-[#FFFFFF]",
  },
  SSK:{
    primary: "#006341",
    secondary: "#FFFFFF",
    primaryBackground: "bg-[#006341]",
    secondaryBorder: "border-[#FFFFFF]",
    secondaryText: "text-[#FFFFFF]",
    simpleText: "text-[#FFFFFF]",
  },
  TOR:{
    primary: "#0C2340",
    secondary: "#5F8FB4",
    primaryBackground: "bg-[#0C2340]",
    secondaryBorder: "border-[#5F8FB4]",
    secondaryText: "text-[#5F8FB4]",
    simpleText: "text-[#FFFFFF]",
  },
  WPG:{
    primary: "#003087",
    secondary: "#B9975B",
    primaryBackground: "bg-[#003087]",
    secondaryBorder: "border-[#B9975B]",
    secondaryText: "text-[#B9975B]",
    simpleText: "text-[#FFFFFF]",
  },
  XXX:{
    primary: "#000000",
    secondary: "#FFFFFF",
    primaryBackground: "bg-[#000000]",
    secondaryBorder: "border-[#FFFFFF]",
    secondaryText: "text-[#FFFFFF]",
    simpleText: "text-[#FFFFFF]",
  },
}