import type { IFLTeamType } from "~/data/CFL/CFLdata";
import type { StyleBookType } from "~/types/StyleBook";

export const IFLstyleData: { [Key in IFLTeamType] : StyleBookType} = {
  ARI: {
    primary: "#000000",
    secondary: "#E97C3A",
    primaryBackground: "bg-[#000000]",
    secondaryBorder: "border-[#E97C3A]",
    secondaryText: "text-[#E97C3A]",
    simpleText: "text-[#FFFFFF]",
  },
  FSH: {
    primary: "#3A738E",
    secondary: "#FBE025",
    primaryBackground: "bg-[#3A738E]",
    secondaryBorder: "border-[#FBE025]",
    secondaryText: "text-[#FBE025]",
    simpleText: "text-[#FFFFFF]",
  },
  GBB: {
    primary: "#003431",
    secondary: "#FFFFFF",
    primaryBackground: "bg-[#003431]",
    secondaryBorder: "border-[#FFFFFF]",
    secondaryText: "text-[#FFFFFF]",
    simpleText: "text-[#FFFFFF]",
  },
  IBS: {
    primary: "#000000",
    secondary: "#C00000",
    primaryBackground: "bg-[#000000]",
    secondaryBorder: "border-[#C00000]",
    secondaryText: "text-[#C00000]",
    simpleText: "text-[#FFFFFF]",
  },
  JAX: {
    primary: "#DD0000",
    secondary: "#000000",
    primaryBackground: "bg-[#DD0000]",
    secondaryBorder: "border-[#000000]",
    secondaryText: "text-[#000000]",
    simpleText: "text-[#FFFFFF]",
  },
  NMC: {
    primary: "#FF0000",
    secondary: "#FFD700",
    primaryBackground: "bg-[#FF0000]",
    secondaryBorder: "border-[#FFD700]",
    secondaryText: "text-[#FFD700]",
    simpleText: "text-[#FFFFFF]",
  },
  NAW: {
    primary: "#166FAB",
    secondary: "#E92330",
    primaryBackground: "bg-[#166FAB]",
    secondaryBorder: "border-[#E92330]",
    secondaryText: "text-[#E92330]",
    simpleText: "text-[#FFFFFF]",
  },
  ORL: {
    primary: "#0F2D5B",
    secondary: "#45B0AC",
    primaryBackground: "bg-[#0F2D5B]",
    secondaryBorder: "border-[#45B0AC]",
    secondaryText: "text-[#45B0AC]",
    simpleText: "text-[#FFFFFF]",
  },
  QCS: {
    primary: "#203971",
    secondary: "#D2B780",
    primaryBackground: "bg-[#203971]",
    secondaryBorder: "border-[#D2B780]",
    secondaryText: "text-[#D2B780]",
    simpleText: "text-[#FFFFFF]",
  },
  SAG: {
    primary: "#0100E4",
    secondary: "#ED1B24",
    primaryBackground: "bg-[#0100E4]",
    secondaryBorder: "border-[#ED1B24]",
    secondaryText: "text-[#ED1B24]",
    simpleText: "text-[#FFFFFF]",
  },
  SDS: {
    primary: "#747B4F",
    secondary: "#1D1E1E",
    primaryBackground: "bg-[#747B4F]",
    secondaryBorder: "border-[#1D1E1E]",
    secondaryText: "text-[#1D1E1E]",
    simpleText: "text-[#FFFFFF]",
  },
  TSS: {
    primary: "#000000",
    secondary: "#F0B31A",
    primaryBackground: "bg-[#000000]",
    secondaryBorder: "border-[#F0B31A]",
    secondaryText: "text-[#F0B31A]",
    simpleText: "text-[#FFFFFF]",
  },
  TUL: {
    primary: "#FDBE14",
    secondary: "#383B42",
    primaryBackground: "bg-[#FDBE14]",
    secondaryBorder: "border-[#383B42]",
    secondaryText: "text-[#383B42]",
    simpleText: "text-[#000000]",
  },
  VEG: {
    primary: "#CE1126",
    secondary: "#B5985A",
    primaryBackground: "bg-[#CE1126]",
    secondaryBorder: "border-[#B5985A]",
    secondaryText: "text-[#B5985A]",
    simpleText: "text-[#FFFFFF]",
  },
}