import type { PWHLTeamType } from "~/data/NHL/NHLdata";
import { type StyleBookType } from "~/types/StyleBook";

export const PWHLstyleData: {[Key in PWHLTeamType] : StyleBookType
} = {
  BOS: {
    primary: "#173F35",
    secondary: "#B5E3D8",
    primaryBackground: "bg-[#173F35]",
    secondaryBorder: "border-[#B5E3D8]",
    secondaryText: "text-[#B5E3D8]",
    simpleText: "text-[#FFFFFF]",
  },
  DET: {
    primary: "#000000",
    secondary: "#C02B2D",
    primaryBackground: "bg-[#000000]",
    secondaryBorder: "border-[#C02B2D]",
    secondaryText: "text-[#C02B2D]",
    simpleText: "text-[#FFFFFF]",
  },
  HAM: {
    primary: "#F2A900",
    secondary: "#64111D",
    primaryBackground: "bg-[#F2A900]",
    secondaryBorder: "border-[#64111D]",
    secondaryText: "text-[#64111D]",
    simpleText: "text-[#FFFFFF]",
  },
  MIN: {
    primary: "#250E62",
    secondary: "#A77BCA",
    primaryBackground: "bg-[#250E62]",
    secondaryBorder: "border-[#A77BCA]",
    secondaryText: "text-[#A77BCA]",
    simpleText: "text-[#FFFFFF]",
  },
  MTL: {
    primary: "#E1D3C4",
    secondary: "#862633",
    primaryBackground: "bg-[#E1D3C4]",
    secondaryBorder: "border-[#862633]",
    secondaryText: "text-[#862633]",
    simpleText: "text-[#000000]",
  },
  NYS: {
    primary: "#00BFB3",
    secondary: "#041E42",
    primaryBackground: "bg-[#00BFB3]",
    secondaryBorder: "border-[#041E42]",
    secondaryText: "text-[#041E42]",
    simpleText: "text-[#FFFFFF]",
  },
  OTT: {
    primary: "#A6192E",
    secondary: "#FFB81C",
    primaryBackground: "bg-[#A6192E]",
    secondaryBorder: "border-[#FFB81C]",
    secondaryText: "text-[#FFB81C]",
    simpleText: "text-[#FFFFFF]",
  },
  SEA: {
    primary: "#0C5256",
    secondary: "#80ADBE",
    primaryBackground: "bg-[#0C5256]",
    secondaryBorder: "border-[#80ADBE]",
    secondaryText: "text-[#80ADBE]",
    simpleText: "text-[#FFFFFF]",
  },
  SJS: {
    primary: "#F69245",
    secondary: "#0774CE",
    primaryBackground: "bg-[#F69245]",
    secondaryBorder: "border-[#0774CE]",
    secondaryText: "text-[#0774CE]",
    simpleText: "text-[#FFFFFF]",
  },
  TOR: {
    primary: "#0067B9",
    secondary: "#FFD100",
    primaryBackground: "bg-[#0067B9]",
    secondaryBorder: "border-[#FFD100]",
    secondaryText: "text-[#FFD100]",
    simpleText: "text-[#FFFFFF]",
  },
  VAN: {
    primary: "#0F4777",
    secondary: "#A76741",
    primaryBackground: "bg-[#0F4777]",
    secondaryBorder: "border-[#A76741]",
    secondaryText: "text-[#A76741]",
    simpleText: "text-[#FFFFFF]",
  },
  VEG: {
    primary: "#717237",
    secondary: "#FAAC2E",
    primaryBackground: "bg-[#717237]",
    secondaryBorder: "border-[#FAAC2E]",
    secondaryText: "text-[#FAAC2E]",
    simpleText: "text-[#FFFFFF]",
  },
}