import type { PWHLTeamType } from "~/data/NHL/NHLdata";
import { type StyleBookType } from "~/types/StyleBook";

export const PWHLstyleData: {[Key in PWHLTeamType] : StyleBookType
} = {
  BOS: {
    primary: "#173F35",
    secondary: "#B5E3D8",
    primaryBackground: "bg-[#173F35]",
    primaryBackgroundHover: "hover:bg-[#173F35]",
    secondaryBorder: "border-[#B5E3D8]",
    secondaryBorderHover: "hover:border-[#B5E3D8]",
    secondaryText: "text-[#B5E3D8]",
    secondaryTextHover: "hover:text-[#B5E3D8]",
    simpleText: "text-[#FFFFFF]",
    simpleTextHover: "hover:text-[#FFFFFF]",
  },
  DET: {
    primary: "#000000",
    secondary: "#C02B2D",
    primaryBackground: "bg-[#000000]",
    primaryBackgroundHover: "hover:bg-[#000000]",
    secondaryBorder: "border-[#C02B2D]",
    secondaryBorderHover: "hover:border-[#C02B2D]",
    secondaryText: "text-[#C02B2D]",
    secondaryTextHover: "hover:text-[#C02B2D]",
    simpleText: "text-[#FFFFFF]",
    simpleTextHover: "hover:text-[#FFFFFF]",
  },
  HAM: {
    primary: "#F2A900",
    secondary: "#64111D",
    primaryBackground: "bg-[#F2A900]",
    primaryBackgroundHover: "hover:bg-[#F2A900]",
    secondaryBorder: "border-[#64111D]",
    secondaryBorderHover: "hover:border-[#64111D]",
    secondaryText: "text-[#64111D]",
    secondaryTextHover: "hover:text-[#64111D]",
    simpleText: "text-[#FFFFFF]",
    simpleTextHover: "hover:text-[#FFFFFF]",
  },
  MIN: {
    primary: "#A77BCA",
    secondary: "#250E62",
    primaryBackground: "bg-[#A77BCA]",
    primaryBackgroundHover: "hover:bg-[#A77BCA]",
    secondaryBorder: "border-[#250E62]",
    secondaryBorderHover: "hover:border-[#250E62]",
    secondaryText: "text-[#250E62]",
    secondaryTextHover: "hover:text-[#250E62]",
    simpleText: "text-[#FFFFFF]",
    simpleTextHover: "hover:text-[#FFFFFF]",
  },
  MTL: {
    primary: "#E1D3C4",
    secondary: "#862633",
    primaryBackground: "bg-[#E1D3C4]",
    primaryBackgroundHover: "hover:bg-[#E1D3C4]",
    secondaryBorder: "border-[#862633]",
    secondaryBorderHover: "hover:border-[#862633]",
    secondaryText: "text-[#862633]",
    secondaryTextHover: "hover:text-[#862633]",
    simpleText: "text-[#000000]",
    simpleTextHover: "hover:text-[#000000]",
  },
  NYS: {
    primary: "#00BFB3",
    secondary: "#041E42",
    primaryBackground: "bg-[#00BFB3]",
    primaryBackgroundHover: "hover:bg-[#00BFB3]",
    secondaryBorder: "border-[#041E42]",
    secondaryBorderHover: "hover:border-[#041E42]",
    secondaryText: "text-[#041E42]",
    secondaryTextHover: "hover:text-[#041E42]",
    simpleText: "text-[#FFFFFF]",
    simpleTextHover: "hover:text-[#FFFFFF]",
  },
  OTT: {
    primary: "#A6192E",
    secondary: "#FFB81C",
    primaryBackground: "bg-[#A6192E]",
    primaryBackgroundHover: "hover:bg-[#A6192E]",
    secondaryBorder: "border-[#FFB81C]",
    secondaryBorderHover: "hover:border-[#FFB81C]",
    secondaryText: "text-[#FFB81C]",
    secondaryTextHover: "hover:text-[#FFB81C]",
    simpleText: "text-[#FFFFFF]",
    simpleTextHover: "hover:text-[#FFFFFF]",
  },
  SEA: {
    primary: "#80ADBE",
    secondary: "#0C5256",
    primaryBackground: "bg-[#80ADBE]",
    primaryBackgroundHover: "hover:bg-[#80ADBE]",
    secondaryBorder: "border-[#0C5256]",
    secondaryBorderHover: "hover:border-[#0C5256]",
    secondaryText: "text-[#0C5256]",
    secondaryTextHover: "hover:text-[#0C5256]",
    simpleText: "text-[#FFFFFF]",
    simpleTextHover: "hover:text-[#FFFFFF]",
  },
  SJS: {
    primary: "#F69245",
    secondary: "#0774CE",
    primaryBackground: "bg-[#F69245]",
    primaryBackgroundHover: "hover:bg-[#F69245]",
    secondaryBorder: "border-[#0774CE]",
    secondaryBorderHover: "hover:border-[#0774CE]",
    secondaryText: "text-[#0774CE]",
    secondaryTextHover: "hover:text-[#0774CE]",
    simpleText: "text-[#FFFFFF]",
    simpleTextHover: "hover:text-[#FFFFFF]",
  },
  TOR: {
    primary: "#0067B9",
    secondary: "#FFD100",
    primaryBackground: "bg-[#0067B9]",
    primaryBackgroundHover: "hover:bg-[#0067B9]",
    secondaryBorder: "border-[#FFD100]",
    secondaryBorderHover: "hover:border-[#FFD100]",
    secondaryText: "text-[#FFD100]",
    secondaryTextHover: "hover:text-[#FFD100]",
    simpleText: "text-[#FFFFFF]",
    simpleTextHover: "hover:text-[#FFFFFF]",
  },
  VAN: {
    primary: "#0F4777",
    secondary: "#A76741",
    primaryBackground: "bg-[#0F4777]",
    primaryBackgroundHover: "hover:bg-[#0F4777]",
    secondaryBorder: "border-[#A76741]",
    secondaryBorderHover: "hover:border-[#A76741]",
    secondaryText: "text-[#A76741]",
    secondaryTextHover: "hover:text-[#A76741]",
    simpleText: "text-[#FFFFFF]",
    simpleTextHover: "hover:text-[#FFFFFF]",
  },
  VEG: {
    primary: "#717237",
    secondary: "#FAAC2E",
    primaryBackground: "bg-[#717237]",
    primaryBackgroundHover: "hover:bg-[#717237]",
    secondaryBorder: "border-[#FAAC2E]",
    secondaryBorderHover: "hover:border-[#FAAC2E]",
    secondaryText: "text-[#FAAC2E]",
    secondaryTextHover: "hover:text-[#FAAC2E]",
    simpleText: "text-[#FFFFFF]",
    simpleTextHover: "hover:text-[#FFFFFF]",
  },
}