import { type AllWNBATeamType } from "~/data/WNBA/WNBAdata";
import { type StyleBookType } from "~/types/StyleBook";

export const WNBAstyleData: {[Key in AllWNBATeamType] : StyleBookType
} = {
  ATL:{
    primary: "#C8102E",
    secondary: "#418FDE",
    primaryBackground: "bg-[#C8102E]",
    secondaryBorder: "border-[#418FDE]",
    secondaryText: "text-[#418FDE]",
    simpleText: "text-[#FFFFFF]",
  },
  CHI:{
    primary: "#418FDE",
    secondary: "#FFCD00",
    primaryBackground: "bg-[#418FDE]",
    secondaryBorder: "border-[#FFCD00]",
    secondaryText: "text-[#FFCD00]",
    simpleText: "text-[#FFFFFF]",
  },
  CON:{
    primary: "#DC4405",
    secondary: "#041E42",
    primaryBackground: "bg-[#DC4405]",
    secondaryBorder: "border-[#041E42]",
    secondaryText: "text-[#041E42]",
    simpleText: "text-[#FFFFFF]",
  },
  DAL:{
    primary: "#0C2340",
    secondary: "#C4D600",
    primaryBackground: "bg-[#0C2340]",
    secondaryBorder: "border-[#C4D600]",
    secondaryText: "text-[#C4D600]",
    simpleText: "text-[#FFFFFF]",
  },
  IND:{
    primary: "#041E42",
    secondary: "#FFCD00",
    primaryBackground: "bg-[#041E42]",
    secondaryBorder: "border-[#FFCD00]",
    secondaryText: "text-[#FFCD00]",
    simpleText: "text-[#FFFFFF]",
  },
  LVA:{
    primary: "#000000",
    secondary: "#BA0C2F",
    primaryBackground: "bg-[#000000]",
    secondaryBorder: "border-[#BA0C2F]",
    secondaryText: "text-[#BA0C2F]",
    simpleText: "text-[#FFFFFF]",
  },
  LAS:{
    primary: "#FFC72C",
    secondary: "#702F8A",
    primaryBackground: "bg-[#FFC72C]",
    secondaryBorder: "border-[#702F8A]",
    secondaryText: "text-[#702F8A]",
    simpleText: "text-[#702F8A]",
  },
  MIN:{
    primary: "#0C2340",
    secondary: "#78BE20",
    primaryBackground: "bg-[#0C2340]",
    secondaryBorder: "border-[#78BE20]",
    secondaryText: "text-[#78BE20]",
    simpleText: "text-[#FFFFFF]",
  },
  NYL:{
    primary: "#003DA5",
    secondary: "#FF671F",
    primaryBackground: "bg-[#003DA5]",
    secondaryBorder: "border-[#FF671F]",
    secondaryText: "text-[#FF671F]",
    simpleText: "text-[#FFFFFF]",
  },
  PHO:{
    primary: "#201747",
    secondary: "#CB6015",
    primaryBackground: "bg-[#201747]",
    secondaryBorder: "border-[#CB6015]",
    secondaryText: "text-[#CB6015]",
    simpleText: "text-[#FFFFFF]",
  },
  POR:{
    primary: "#C8102E",
    secondary: "#3F3735",
    primaryBackground: "bg-[#C8102E]",
    secondaryBorder: "border-[#3F3735]",
    secondaryText: "text-[#3F3735]",
    simpleText: "text-[#FFFFFF]",
  },
  SEA:{
    primary: "#2C5234",
    secondary: "#FBE122",
    primaryBackground: "bg-[#2C5234]",
    secondaryBorder: "border-[#FBE122]",
    secondaryText: "text-[#FBE122]",
    simpleText: "text-[#FFFFFF]",
  },
  TOR:{
    primary: "#441E36",
    secondary: "#B3C7E7",
    primaryBackground: "bg-[#441E36]",
    secondaryBorder: "border-[#B3C7E7]",
    secondaryText: "text-[#B3C7E7]",
    simpleText: "text-[#FFFFFF]",
  },
  WAS:{
    primary: "#0C2340",
    secondary: "#C8102E",
    primaryBackground: "bg-[#0C2340]",
    secondaryBorder: "border-[#C8102E]",
    secondaryText: "text-[#C8102E]",
    simpleText: "text-[#FFFFFF]",
  },
  CHO:{
    primary: "#299BA1",
    secondary: "#37124E",
    primaryBackground: "bg-[#299BA1]",
    secondaryBorder: "border-[#37124E]",
    secondaryText: "text-[#37124E]",
    simpleText: "text-[#FFFFFF]",
  },
  DET:{
    primary: "#006CBD",
    secondary: "#FF0045",
    primaryBackground: "bg-[#006CBD]",
    secondaryBorder: "border-[#FF0045]",
    secondaryText: "text-[#FF0045]",
    simpleText: "text-[#FFFFFF]",
  },
  GSV:{
    primary: "#9C59D4",
    secondary: "#000000",
    primaryBackground: "bg-[#9C59D4]",
    secondaryBorder: "border-[#000000]",
    secondaryText: "text-[#000000]",
    simpleText: "text-[#FFFFFF]",
  },
  HOU:{
    primary: "#CE0B40",
    secondary: "#00265D",
    primaryBackground: "bg-[#CE0B40]",
    secondaryBorder: "border-[#00265D]",
    secondaryText: "text-[#00265D]",
    simpleText: "text-[#FFFFFF]",
  },
  SAC:{
    primary: "#8033C4",
    secondary: "#8C9093",
    primaryBackground: "bg-[#8033C4]",
    secondaryBorder: "border-[#8C9093]",
    secondaryText: "text-[#8C9093]",
    simpleText: "text-[#FFFFFF]",
  },
  SAS:{
    primary: "#C4CED4",
    secondary: "#000000",
    primaryBackground: "bg-[#C4CED4]",
    secondaryBorder: "border-[#000000]",
    secondaryText: "text-[#000000]",
    simpleText: "text-[#000000]",
  },
};