import { type NextPage } from "next";
import Head from "next/head";
import { useNavContext } from "~/hooks/useNavContext";
import NavBar from "~/components/Nav/NavBar";
import NBApickTable from "~/components/NBA/NBApickTable";

const NBA: NextPage = () => {
  const { navState, navDispatch } = useNavContext();
  const { pageMode, underPageMode } = navState;
  return (
    <>
      <Head>
        <title>NBA Future Draft Picks</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col bg-gradient-to-r from-nba/50 via-white to-nba/50 sm:items-center">
        <NavBar />
        <div className="mx-auto flex flex-col items-start overflow-auto bg-white sm:m-0 sm:max-w-screen-sm sm:items-center">
          {underPageMode === "Future Picks" && <NBApickTable />}
        </div>
      </main>
    </>
  );
};

export default NBA;
