import { type NextPage } from "next";
import Head from "next/head";
import { useNavContext } from "~/hooks/useNavContext";
import NavBar from "~/components/Nav/NavBar";
import { NBARankContextProvider } from "~/context/NBArankContext";
import NBARanker from "~/components/NBA/NBARanker";
import NBApickTable from "~/components/NBA/NBApickTable";

const NBA: NextPage = () => {
  const { navState } = useNavContext();
  const { underPageMode } = navState;
  return (
    <>
      <Head>
        <title>NBA Future Draft Picks</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col bg-gradient-to-r from-nba/50 via-white to-nba/50 sm:items-center">
        <NavBar />
        <div className="mx-auto flex w-full flex-col items-center bg-white sm:m-0 sm:max-w-screen-sm">
          {underPageMode === "Future Picks" && <NBApickTable />}
          {underPageMode === "Rank" && (
            <NBARankContextProvider>
              <NBARanker />
            </NBARankContextProvider>
          )}
        </div>
      </main>
    </>
  );
};

export default NBA;
