import { type NextPage } from "next";
import Head from "next/head";
import NavBar from "~/components/Nav/NavBar";
import Ranker from "~/components/Rank/Ranker";

const NFL: NextPage = () => {
  return (
    <>
      <Head>
        <title>NFL</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col bg-gradient-to-r from-nfl/50 via-white to-nfl/50 sm:items-center">
        <NavBar />
        <div className="mx-auto flex flex-col items-start bg-white sm:m-0 sm:max-w-screen-sm sm:items-center">
          <Ranker />
        </div>
      </main>
    </>
  );
};

export default NFL;
