import { type NextPage } from "next";
import Head from "next/head";
import { useNavContext } from "~/hooks/useNavContext";
import NavBar from "~/components/Nav/NavBar";
import { NFLRankContextProvider } from "~/context/NFLrankContext";
import NFLRanker from "~/components/NFL/NFLRanker";
import NFLSchedule from "~/components/NFL/Schedule";

const NFL: NextPage = () => {
  const { navState } = useNavContext();
  const { underPageMode } = navState;
  return (
    <>
      <Head>
        <title>NFL</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col bg-gradient-to-r from-nfl/50 via-white to-nfl/50 sm:items-center">
        <NavBar pageMode="NFL" underPageMode="Schedule" />
        <div className="mx-auto flex w-full grow flex-col items-start bg-white sm:m-0 sm:max-w-screen-sm sm:items-center md:max-w-screen-md lg:max-w-screen-lg">
          {underPageMode === "Schedule" && <NFLSchedule />}
          {underPageMode === "Rank" && (
            <NFLRankContextProvider>
              <NFLRanker />
            </NFLRankContextProvider>
          )}
        </div>
        <div className="w-full bg-nfl p-2 text-center text-white">
          Developed by{" "}
          <a
            className="hover:underline"
            href="https://shawnweddle.com/"
            target="_blank"
            rel="noopener noreferrer"
          >
            Shawn Weddle
          </a>
        </div>
      </main>
    </>
  );
};

export default NFL;
