import { type NextPage } from "next";
import Head from "next/head";
import { useNavContext } from "~/hooks/useNavContext";
import NavBar from "~/components/Nav/NavBar";
import { NFLRankContextProvider } from "~/context/NFLrankContext";
import NFLRanker from "~/components/NFL/NFLRanker";

const NFL: NextPage = () => {
  const { navState } = useNavContext();
  const { underPageMode } = navState;
  return (
    <>
      <Head>
        <title>NFL</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col bg-gradient-to-r from-nfl/50 via-white to-nfl/50 sm:items-center">
        <NavBar />
        <div className="mx-auto flex w-full flex-col items-center bg-white sm:m-0 sm:max-w-screen-sm">
          {underPageMode === "Rank" && (
            <NFLRankContextProvider>
              <NFLRanker />
            </NFLRankContextProvider>
          )}
        </div>
      </main>
    </>
  );
};

export default NFL;
