import { type NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import {
  teamColorStyles,
  teamInfo,
  teamColors,
  initialUnrankedTeams,
  initialRankedTeams,
} from "../data/NFLdata";
import type { teamInfoType } from "../data/NFLdata";

const NFLRank: NextPage = () => {
  const [unRankedTeams, setUnrankedTeams] =
    useState<teamInfoType[]>(initialUnrankedTeams);
  const [rankedTeams, setRankedTeams] =
    useState<(teamInfoType | { code: "RRR" })[]>(initialRankedTeams);

  const teamList = rankedTeams.map((team, index) => {
    const activeRankedTeamInfo = team;
    const activeUnrankedTeamInfo = unRankedTeams[index];
    const activeUnrankedTeamCode = activeUnrankedTeamInfo?.code ?? "";
    const activeUnrankedTeamColorStyle =
      teamColorStyles[activeUnrankedTeamCode]?.primary ?? "text-white bg-black";
    return (
      <tr
        key={index}
        className="text-center text-sm font-bold odd:bg-indigo-200"
      >
        <td className={activeUnrankedTeamColorStyle}>
          {activeUnrankedTeamInfo?.location} {activeUnrankedTeamInfo?.name}
        </td>
        <td className="px-1">
          <input
            type="number"
            className="w-8 rounded-l-md outline-indigo-800"
          />
          <button className="rounded-r-md bg-indigo-800 px-1 text-white hover:bg-indigo-700">
            ⮞
          </button>
        </td>
        <td> </td>
        <td>
          <button className="rounded-md bg-red-600 px-1 text-white hover:bg-red-500">
            ⮜
          </button>
        </td>
        <td className="px-1">{index + 1}</td>
        <td className="bg-black px-1 text-white">- - - - -</td>
        <td className="px-1">
          <input
            type="number"
            className="w-8 rounded-l-md outline-indigo-800"
          />
          <button className="rounded-r-md bg-indigo-800 px-1 text-white hover:bg-indigo-700">
            ⮞
          </button>
        </td>
        <td className="px-1">
          <button className="rounded-l-md bg-teal-600 px-1 text-white hover:bg-teal-500">
            ⮝
          </button>
          <button className="rounded-r-md bg-teal-600 px-1 text-white hover:bg-teal-500">
            ⮟
          </button>
        </td>
      </tr>
    );
  });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-indigo-900 to-indigo-950">
        <div className="bg-indigo-100">
          <table>
            <thead>
              <tr>
                <th>Z</th>
                <th>1</th>
                <th>2</th>
                <th>3</th>
                <th>4</th>
                <th>5</th>
                <th>6</th>
                <th>7</th>
              </tr>
            </thead>
            <tbody>{teamList}</tbody>
          </table>
        </div>
      </main>
    </>
  );
};

export default NFLRank;
