import { type NextPage } from "next";
import Head from "next/head";
import { useNavContext } from "~/hooks/useNavContext";
import NavBar from "~/components/Nav/NavBar";
import { NHLRankContextProvider } from "~/context/NHLrankContext";
import NHLRanker from "~/components/NHL/NHLRanker";
import StanleyCupSeriesList from "~/components/NHL/StanleyCupSeriesList";

const NHL: NextPage = () => {
  const { navState } = useNavContext();
  const { underPageMode } = navState;
  return (
    <>
      <Head>
        <title>NHL</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col bg-gradient-to-r from-nhl/50 via-white to-nhl/50 sm:items-center">
        <NavBar pageMode="NHL" underPageMode="Stanley Cups" />
        <div className="mx-auto flex w-full grow flex-col items-start bg-white sm:m-0 sm:max-w-screen-sm sm:items-center md:max-w-screen-md lg:max-w-screen-lg">
          {underPageMode === "Rank" && (
            <NHLRankContextProvider>
              <NHLRanker />
            </NHLRankContextProvider>
          )}
          {underPageMode === "Stanley Cups" && <StanleyCupSeriesList />}
        </div>
        <div className="w-full bg-nhl p-2 text-center text-white">
          Developed by{" "}
          <a
            className="hover:underline"
            href="https://shawnweddle.com/"
            target="_blank"
            rel="noopener noreferrer"
          >
            Shawn Weddle
          </a>
        </div>
      </main>
    </>
  );
};

export default NHL;
