import { type NextPage } from "next";
import Head from "next/head";
import NEWpickTable from "~/components/NBApickTable";

const Work: NextPage = () => {
  return (
    <>
      <Head>
        <title>Work</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center bg-gray-800">
        <div className="text-2xl text-white">NBA Future Draft Picks</div>
        <NEWpickTable />
      </main>
    </>
  );
};

export default Work;
